NetCore/Controllers/BlogController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCore.Controllers
{
    
    [AllowAnonymous]
    public class BlogController : Controller
    {
        MakaleManager veri = new MakaleManager(new EfMakaleDal());

        public IActionResult Blog()
        {
            var list = veri.MakaleListele();
            return View(list);
        }

        public IActionResult BlogDetay(int id)
        {
            ViewBag.id = id;
            
            var list = veri.IdGore(id);
            ViewBag.yid = list.Id;
            return View(list);
        }
    }
}

NetCore/Controllers/MesajController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NetCore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCore.Controllers
{
    public class MesajController : Controller
    {
        MesajManager list = new MesajManager(new EfMesajDal());
        UserManager<AppUser> _userManager;
        
        public MesajController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> Mesajlar()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var veri = list.YazarMesaj(user.Id);
            return View(veri);
        }

        [HttpGet]
        public IActionResult MesajGonder()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> MesajGonder(MesajGön p)
        {
            var alici = await _userManager.FindByNameAsync(p.aliciAdi);
            var gönderen = await _userManager.FindByNameAsync(User.Identity.Name);
            if (alici != null)
            {
                Mesaj mesaj = new Mesaj()
                {
                    MesajAlici = alici.Id,
                    MesajGönderen = gönderen.Id,
                    MesajAciklama = p.mesajAciklama,
                    MesajTarih = p.mesajTarih,
                };

                list.ekle(mesaj);
                return RedirectToAction("Mesajlar");
            }
            ViewBag.hata = 1;
            return View(p);
        }

        public IActionResult MesajDetay(int id)
        {
            var veri = list.MesajDetay(id);
            veri.MesajStatu = true; // Bildirimlere gelen mesaj adeti statü'ye göre çağırılması için ayrı bir metod oluşturulacak
            list.güncelle(veri);
            return View(veri);
        }
    }
}

NetCore/Controllers/YazarDashBoardController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCore.Controllers
{
    public class YazarDashBoardController : Controller
    {
        MakaleManager list = new MakaleManager(new EfMakaleDal());
        KategoriManager list2 = new KategoriManager(new EfKategoriDal());
        

        UserManager<AppUser> _userManager;

        public YazarDashBoardController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> DashBoard()
        {
            var user =await _userManager.FindByNameAsync(User.Identity.Name);
            ViewBag.veri1 = list.MakaleCount();
            ViewBag.veri2 = list.YazarMakCount(user.Id);
            ViewBag.veri3 = list2.KategoriCount();
            return View();
        }
    }
}

NetCore/Views/Shared/Components/_YazarNavbar/Default.cshtml
@{
    Layout = null;
}

<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        @await Component.InvokeAsync("_YazarProfil") 
        <li class="nav-item">
            <a class="nav-link" asp-controller="YazarDashBoard" asp-action="DashBoard">
                <span class="menu-title">Dashboard</span>
                <i class="mdi mdi-home menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Yazar" asp-action="MakaleList">
                <span class="menu-title">Bloglarım</span>
                <i class="mdi mdi-format-list-bulleted menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Yazar" asp-action="YazarBilgi">
                <span class="menu-title">Profilim</span>
                <i class="mdi mdi-contacts menu-icon"></i>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" asp-controller="Yazar" asp-action="MakaleEkle">
                <span class="menu-title">Yeni Blog</span>
                <i class="mdi mdi-chart-bar menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Yazar" asp-action="Bildirimler">
                <span class="menu-title">Bildirimler</span>
                <i class="mdi mdi-chart-bar menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Mesaj" asp-action="Mesajlar">
                <span class="menu-title">Mesajlar</span>
                <i class="mdi mdi-chart-bar menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Blog" asp-action="Blog">
                <span class="menu-title">Siteye Dön</span>
                <i class="mdi mdi-chart-bar menu-icon"></i>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" asp-controller="Widgets" asp-action="Widgets" asp-area="Admin">
                <span class="menu-title">Admin</span>
                <i class="mdi mdi-chart-bar menu-icon"></i>
            </a>
        </li>
    </ul>
</nav>