NetCore/Areas/Admin/Controllers/AdminBlogController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="Admin")]
    public class AdminBlogController : Controller
    {
        MakaleManager blog = new MakaleManager(new EfMakaleDal());

      

        public IActionResult Bloglar()
        {
            var list = blog.MakaleAdmin();
            return View(list);
        }

        public IActionResult StatuFalse(int id)
        {
            var guncellenen=blog.IdGore(id);
            guncellenen.MakaleStatu = false;
            blog.güncelle(guncellenen);

            return RedirectToAction("Bloglar");
        }

        public IActionResult StatuTrue(int id)
        {
            var guncellenen = blog.IdGore(id);
            guncellenen.MakaleStatu = true;
            blog.güncelle(guncellenen);

            return RedirectToAction("Bloglar");
        }

    }
}

NetCore/Areas/Admin/Views/AdminBlog/Bloglar.cshtml
@{
    ViewData["Title"] = "Bloglar";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@using EntityLayer.Concrete
@model List<Makale>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-3">
                <div class="ibox">
                    <div class="ibox-content product-box">

                        <div>
                            <img src=@item.MakaleImgUrl height="225" width="250" />
                        </div>
                        <div class="product-desc">

                            @{
                                if (item.MakaleStatu == true)
                                {
                                    <span class="label label-info float-right">Yayında</span>
                                }
                                else
                                {
                                    <span class="label label-danger float-right">Yayında Değil</span>
                                }
                            }

                            <small class="text-muted">@item.Kategori.KategoriAdi</small>
                            <a href="/Blog/BlogDetay/@item.MakaleId" class="product-name">@item.MakaleBaslik</a>



                            <div class="small m-t-xs">
                                @item.MakaleAciklama.Substring(0, 50) ...
                            </div>
                            <div class="m-t text-righ">

                                <a asp-area="Admin" asp-controller="AdminBlog" asp-action="StatuTrue" asp-route-id=@item.MakaleId class="btn btn-xs  btn-primary">Yayına Al  </a>
                                <a asp-area="Admin" asp-controller="AdminBlog" asp-action="StatuFalse" asp-route-id=@item.MakaleId class="btn btn-xs  btn-danger">Yayından Kaldır  </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</div>